### ISSUE TITLE
Ball end G-code generator - eliptic curve

### ISSUE THREAD

**Issue by KyrreKnive** [kachurovskiy/lathecode#4]
Hi Maxim,

I am trying to generate a ball end, but my input seems to generate an unevan curve on the left side.
STOCK D10
TOOL ROUND R0.2 L1.5

L4 DS0 DE8 CONV

L3.464 DS8 DE4 CONV ; 3.464 is the legth from center where the diameter = 4
L4 D4

**Comment by kachurovskiy** [comment]
Did you mean RECT tool instead of ROUND?

First workaround is to define the full sphere but use the cutter that can't cut into the deep part e.g. parting blade:

![image](https://github.com/kachurovskiy/lathecode/assets/517919/eb3dedd6-551a-4b60-81ac-e133a8641a17)

Second workaround is draw the picture on figma.com with your exact dimensions (1px = 0.01mm) and use `From image` button.

**Comment by KyrreKnive** [comment]
Thank's for the workarounds! 
Can you post the calculation (program lines) for the curve /elipse function (L3.464 DS8 DE4 CONV ) ?

**Comment by kachurovskiy** [comment]
> Can you post the calculation (program lines) for the curve /elipse function (L3.464 DS8 DE4 CONV ) ?

@KyrreKnive is https://github.com/kachurovskiy/lathecode/blob/main/src/planner/painter.ts#L86 what you're looking for?
